### ISSUE TITLE
Использование служебного слова

### ISSUE THREAD

**Issue by SimonOsipov** [zakharovdm/Movie_bot#3]
https://github.com/zakharovdm/Movie_bot/blob/4d6e303c0f172b1cba1e2351d4431cc2a093c480/movie_bot.py#L186

`list` это метод. Не стоит использовать его в качестве переменной.
Например, потому что внутри этого цикла ты не сможешь использовать метод `list()`

1. Открой консоль
2. Создай переменную `list = 'Storytell'`
3. Переведи переменную `list` в список методом `list()` 

Также стоит почитать про [keywords](https://www.programiz.com/python-programming/keyword-list)

**Comment by zakharovdm** [comment]
Уже не актуально
