### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by SimonOsipov** [zakharovdm/Movie_bot#6]
```
Traceback (most recent call last):
  File "movie_bot.py", line 4, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

Модуль requests нет в requirements.

**Comment by SimonOsipov** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Пофиксить багу](https://trello.com/c/V2qAnO9L/33-%D0%BF%D0%BE%D1%84%D0%B8%D0%BA%D1%81%D0%B8%D1%82%D1%8C-%D0%B1%D0%B0%D0%B3%D1%83)

**Comment by zakharovdm** [comment]
добавил
